config/routes.rb
Rails.application.routes.draw do
  root to: 'invoices#index'
  resources :invoices, path_names: { invoices: "dashboard" }
  resources :items
  match '*path', to: ->(env) { [404, {}, ['Oops Something Went Wrong...Check URL']] }, via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :items

  validates :total, presence: true
  validates :due, presence: true
  validates :status, presence: true
  validates :description, presence: true
  validates :invoice_number, uniqueness: true

  before_save :set_invoice_number

  private
  def set_invoice_number
    self.invoice_number = SecureRandom.alphanumeric(5)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :invoice

  validates :name, presence: true
  validates :qty, presence: true
  validates :cost, presence: true
  validates :invoice_id, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy]

  require 'pry'

  def index
    case params['filter']
    when 'Paid'
      @invoices = Invoice.where(status: params['filter'])
    when 'Completed'
      @invoices = Invoice.where(status: params['filter'])
    when 'Total'
      @invoices = Invoice.order(total: :desc)
    else
      @invoices = Invoice.all
    end
  end

  def show
    @items = @invoice.items
    @total = @items.sum(:cost)
    @invoice.update(total:@total)
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:total, :due, :status, :description)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_invoice

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to invoice_url(@invoice) }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html {redirect_to invoice_url(@invoice), notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end


   # Only allow a list of trusted parameters through.
   def item_params
    params.permit(:name, :qty, :cost, :invoice_id)
  end

  def set_invoice
    @invoice = Invoice.find(params[:invoice_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="field">
    <%= form.label :due %>
    <%= form.date_select :due %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ["Paid", "Completed"] %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit class: 'form-submit-button' %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>
<div class="main-content-header">
  <div>
    <h1>Invoices</h1>
    <p>There are <%= @invoices.length %> total Invoices</p>
  </div>

  <div class="header-right">
    <form action="/invoices" method="GET">
      <select name="filter" id="filter" onchange=this.form.submit() class="filter">
        <option value="">Filter by</option>
        <option value="Paid">Paid</option>
        <option value="Completed">Completed</option>
        <option value="Total">Total Cost</option>

      </select>
    </form>
    <button><i class="fas fa-plus add-icon"></i><%= link_to 'New Invoice', new_invoice_path %></button>
  </div>
</div>
<div class="main-content-content">
  <ul>
    <% @invoices.each do |invoice| %>
      <li class="invoice-item">
        <p class="invoice-number"><span class="number-icon">#</span><%= invoice.invoice_number %></p>
        <p class="name-date">Due <%= invoice.due %></p>
        <p class="name-date">Client Name</p>
        <p class="total"><%= number_to_currency(invoice.total) %></p>
        <% if invoice.status === 'Completed' %>
          <p class="status-completed"><i class="fas fa-circle status-circle"></i> <%= invoice.status %></p>
        <% else %>
          <p class="status-pending"><i class="fas fa-circle status-circle"></i> <%= invoice.status %></p>
        <% end %>
        <%= link_to '', invoice, class: 'fas fa-chevron-right invoice-arrow'%>

      </li>
    <% end %>
  </ul>
</div>

app/views/invoices/new.html.erb
<div class="page-container-form">
  <div class="form-container">

    <div class="form-header">
      <h3>New Invoice</h3>
      <%= link_to '', invoices_path, class:'fas fa-times exit-form-button' %>
    </div>

    <%= render 'form', invoice: @invoice %>

  </div>
</div>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>
<div class="invoice-show-container">
  <section class="left-column">
      <h1>#<%= @invoice.invoice_number %></h1>
      <table>
        <tr>
          <th>Date Completed</th>
          <th>Total Cost</th>
        </tr>
        <tr>
          <td><%= @invoice.due %></td>
          <td><%= number_to_currency(@invoice.total) %></td>
        </tr>
        <tr>
          <th>Project Description</th>
        </tr>
        <tr>
          <td><%= @invoice.description %></td>
        </tr>
      </table>
  </section>
  <section class="right-column">
    <h3>Item List</h3>
    <table>
      <tr class="item-headers">
        <th>Name</th>
        <th>Qty</th>
        <th>Cost</th>
      </tr>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= item.qty %></td>
          <td><%= item.cost %></td>
          <td class="trash-icon"><%= link_to '', item_url(item, invoice_id: @invoice.id), method: :delete, class: 'fas fa-trash' %></td>
          <!-- <%= link_to '', item_path(item), method: :delete, class: 'fas fa-trash' %> -->
        </tr>
      <% end %>
    </table>
    <%= render '/items/form', invoice: @invoice.id %>
  </section>

    <!-- <%= link_to 'Edit', edit_invoice_path(@invoice) %> |
    <%= link_to 'Back', invoices_path %> -->
</div>

app/views/items/_form.html.erb
<%= form_with(url: items_url, method: 'POST' ) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label 'QTY' %>
    <%= form.number_field :qty%>
  </div>

  <div class="field">
    <%= form.label 'Cost' %>
    <%= form.number_field :cost, step: 0.5 %>
  </div>

  <%= form.hidden_field :invoice_id, value:invoice %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  </head>

  <body>
    <div class="dashboard-container">
      <%= render '/partials/sidebar' %>
      <div class="main-content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<section class="sidebar">
  <!-- <button class="fas fa-home home-button"><%= link_to '', root_path %></button> -->
  <a href="/" class="fas fa-home home-button"></a>
</section>